name: ExploreTheBuild
version: ${project.version}
main: dev.just.explorethebuild.Main
api-version: 1.17
commands:
  status:
    description: Setzt den Status eines Nutzers.
  start:
    description: Startet und stoppt das Event.
  setspawn:
    description: Setzt den Spawnpunkt.
  settpup:
    description: Setzt den Punkt fürs Teleportieren nach oben.
  toggleend:
    description: Ändere den Status des End-Events.