name: Build spigot plugin
on: [push]
jobs:
  build:
    name: Build using maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Build using maven
        run: mvn clean package
      - uses: actions/upload-artifact@v4
        with:
          path: target/*.jar