name: Build spigot plugin
on: [push]
jobs:
  build:
    name: Build using maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Build using maven
        run: mvn clean package
      - uses: actions/upload-artifact@v4
        with:
          path: target/*.jar
          name: plugin_jar
  test:
    name: Test using spigot
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: plugin_jar
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Download PaperMC
        uses: just-dev-creator/install-paper@v1.0.1
        with:
          path: './paperclip.jar'
      - name: Agree to EULA
        run: echo "eula=true" > eula.txt
      - name: Create plugins folder
        run: mkdir plugins
      - name: Copy plugin to plugins folder
        run: cp ExploreTheBuild*.jar plugins/
      - name: Run PaperMC
        run: "java -Xms1024M -Xmx1024M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar paperclip.jar --nogui"
        timeout-minutes: 3
        env:
          GH_ACTIONS: true